FROM microsoft/dotnet:1.1.2-sdk

ENV DOTNET_USE_POLLING_FILE_WATCHER 1

COPY ./src/Voidwell/Voidwell.csproj /tmp/Voidwell.csproj

WORKDIR /tmp

RUN dotnet restore

WORKDIR /Voidwell

ENTRYPOINT dotnet watch run
