<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Voidwell.Platform.Api\Voidwell.Platform.Api.csproj" />
  </ItemGroup>

</Project>
