// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voidwell.Platform.Data;

#nullable disable

namespace Voidwell.Platform.Data.Migrations
{
    [DbContext(typeof(VoidwellDbContext))]
    partial class VoidwellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Voidwell.Platform.Data.Models.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown_content");

                    b.Property<DateTimeOffset>("PublishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_blog_posts");

                    b.ToTable("blog_posts", (string)null);
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.BlogPostTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_blog_post_tags");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_post_tags_normalized_name");

                    b.ToTable("blog_post_tags", (string)null);
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.BlogPostTagMap", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("blog_post_id");

                    b.Property<Guid>("BlogPostTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("blog_post_tag_id");

                    b.HasKey("BlogPostId", "BlogPostTagId")
                        .HasName("pk_blog_post_tag_maps");

                    b.HasIndex("BlogPostTagId")
                        .HasDatabaseName("ix_blog_post_tag_maps_blog_post_tag_id");

                    b.ToTable("blog_post_tag_maps", (string)null);
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.CustomEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("GameId")
                        .HasColumnType("text")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("MapId")
                        .HasColumnType("text")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ScoreConfiguration")
                        .HasColumnType("text")
                        .HasColumnName("score_configuration");

                    b.Property<string>("ServerId")
                        .HasColumnType("text")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_custom_event");

                    b.ToTable("custom_event", (string)null);
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.CustomEventTeam", b =>
                {
                    b.Property<int>("CustomEventId")
                        .HasColumnType("integer")
                        .HasColumnName("custom_event_id");

                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("CustomEventId", "TeamId")
                        .HasName("pk_custom_event_team");

                    b.ToTable("custom_event_team", (string)null);
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.BlogPostTagMap", b =>
                {
                    b.HasOne("Voidwell.Platform.Data.Models.BlogPost", "BlogPost")
                        .WithMany("BlogPostTagMaps")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blog_post_tag_maps_blog_posts_blog_post_id");

                    b.HasOne("Voidwell.Platform.Data.Models.BlogPostTag", "BlogPostTag")
                        .WithMany()
                        .HasForeignKey("BlogPostTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blog_post_tag_maps_blog_post_tags_blog_post_tag_id");

                    b.Navigation("BlogPost");

                    b.Navigation("BlogPostTag");
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.CustomEventTeam", b =>
                {
                    b.HasOne("Voidwell.Platform.Data.Models.CustomEvent", "CustomEvent")
                        .WithMany("Teams")
                        .HasForeignKey("CustomEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_event_team_custom_event_custom_event_id");

                    b.Navigation("CustomEvent");
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.BlogPost", b =>
                {
                    b.Navigation("BlogPostTagMaps");
                });

            modelBuilder.Entity("Voidwell.Platform.Data.Models.CustomEvent", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
