// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Voidwell.Internal.Data;

namespace Voidwell.Internal.Data.Migrations.VoidwellDb
{
    [DbContext(typeof(VoidwellDbContext))]
    partial class VoidwellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Voidwell.Internal.Data.Models.DbBlogPost", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTimeOffset>("PublishDate");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BlogPost");
                });

            modelBuilder.Entity("Voidwell.Internal.Data.Models.DbCustomEvent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("GameId");

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("MapId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ServerId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("CustomEvent");
                });

            modelBuilder.Entity("Voidwell.Internal.Data.Models.DbCustomEventTeam", b =>
                {
                    b.Property<string>("EventId");

                    b.Property<string>("TeamId");

                    b.Property<string>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("EventId", "TeamId");

                    b.HasIndex("Id");

                    b.ToTable("CustomEventTeam");
                });

            modelBuilder.Entity("Voidwell.Internal.Data.Models.DbCustomEventTeam", b =>
                {
                    b.HasOne("Voidwell.Internal.Data.Models.DbCustomEvent")
                        .WithMany("Teams")
                        .HasForeignKey("Id");
                });
#pragma warning restore 612, 618
        }
    }
}
