// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Voidwell.Internal.Data;

namespace Voidwell.Internal.Data.Migrations
{
    [DbContext(typeof(VoidwellDbContext))]
    partial class VoidwellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Voidwell.Internal.Data.Models.BlogPost", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnName("publish_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_blog_post");

                    b.ToTable("blog_post");
                });

            modelBuilder.Entity("Voidwell.Internal.Data.Models.CustomEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("end_date");

                    b.Property<string>("GameId")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsPrivate")
                        .HasColumnName("is_private");

                    b.Property<string>("MapId")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.Property<string>("ScoreConfiguration")
                        .HasColumnName("score_configuration");

                    b.Property<string>("ServerId")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_custom_event");

                    b.ToTable("custom_event");
                });

            modelBuilder.Entity("Voidwell.Internal.Data.Models.CustomEventTeam", b =>
                {
                    b.Property<int>("CustomEventId")
                        .HasColumnName("custom_event_id");

                    b.Property<string>("TeamId")
                        .HasColumnName("team_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.HasKey("CustomEventId", "TeamId")
                        .HasName("pk_custom_event_team");

                    b.ToTable("custom_event_team");
                });

            modelBuilder.Entity("Voidwell.Internal.Data.Models.CustomEventTeam", b =>
                {
                    b.HasOne("Voidwell.Internal.Data.Models.CustomEvent", "CustomEvent")
                        .WithMany("Teams")
                        .HasForeignKey("CustomEventId")
                        .HasConstraintName("fk_custom_event_team_custom_event_custom_event_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
