<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZiggyCreatures.FusionCache" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Voidwell.Platform.Clients.Test" />
  </ItemGroup>

</Project>
